services:
  php:
    build: ./
    volumes:
      - "${PHP_VOLUME:-./src}:/var/www/html/"
    ports:
      - "80:80"

  db:
    container_name: db_todo_pdo_server
    image: mariadb
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: "todo"
      MARIADB_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db_todo_pdo_server
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
